//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeopleComments
    {
        public int commentID { get; set; }
        public int personID { get; set; }
        public System.DateTime commentDate { get; set; }
        public int commentPersonID { get; set; }
        public string comment { get; set; }
        public bool flag { get; set; }
    }
}
