//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriorityProjects
    {
        public int projectID { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string priorityLevel { get; set; }
        public string priorityReason { get; set; }
        public Nullable<int> priorityCreatorID { get; set; }
    
        protected virtual Projects Projects { get; set; }
    }
}
