//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDocuments
    {
        public int projectDocumentID { get; set; }
        public int projectID { get; set; }
        public string documentLink { get; set; }
        public string documentTitle { get; set; }
        public string filePath { get; set; }
        public string documentSource { get; set; }
    
        protected virtual Projects Projects { get; set; }
    }
}
