//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCourses
    {
        public int studentCourseID { get; set; }
        public int studentID { get; set; }
        public string courseID { get; set; }
        public string semester { get; set; }
        public Nullable<int> year { get; set; }
        public string grade { get; set; }
        public Nullable<decimal> mark { get; set; }
    
        protected virtual Students Students { get; set; }
        protected virtual Course Course { get; set; }
    }
}
