//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeopleContacts
    {
        public int personID { get; set; }
        public string contactMethod { get; set; }
        public string contactValue { get; set; }
        public bool preferred { get; set; }
        public System.DateTime dateCreated { get; set; }
        public Nullable<System.DateTime> dateEnded { get; set; }
    }
}
