//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanCourses
    {
        public int planId { get; set; }
        public string courseId { get; set; }
        public string temp { get; set; }
    
        protected virtual Course Course { get; set; }
        protected virtual Plans Plans { get; set; }
    }
}
