//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projects()
        {
            this.projectDuration = 4;
            this.projectSemester = "SP2";
            this.PriorityProjects = new HashSet<PriorityProjects>();
            this.ProjectDocuments = new HashSet<ProjectDocuments>();
            this.ProjectMethodsApplied = new HashSet<ProjectMethodsApplied>();
            this.ProjectPeopleAllocations = new HashSet<ProjectPeopleAllocations>();
            this.StudentProjectRanking = new HashSet<StudentProjectRanking>();
            this.ProjectEffortsApplied = new HashSet<ProjectEffortsApplied>();
        }
    
        public int projectID { get; set; }
        public string projectTitle { get; set; }
        public string projectScope { get; set; }
        public string projectOutcomes { get; set; }
        public int projectDuration { get; set; }
        public string projectPlacementRequirements { get; set; }
        public bool projectSponsorAgreement { get; set; }
        public int projectStatus { get; set; }
        public string projectStatusComment { get; set; }
        public Nullable<System.DateTime> projectStatusChangeDate { get; set; }
        public string projectSemester { get; set; }
        public string projectSemesterCode { get; set; }
        public int projectYear { get; set; }
        public Nullable<int> projectSequenceNo { get; set; }
        public string honoursUndergrad { get; set; }
        public bool requirementsMet { get; set; }
        public int projectCreatorID { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string projectEffortRequirements { get; set; }
        public string Id { get; set; }
        public string projectCode { get; set; }
        public bool austCitizenOnly { get; set; }
        public int studentsReq { get; set; }
        public Nullable<int> scholarshipAmt { get; set; }
        public string scholarshipDetail { get; set; }
        public Nullable<System.DateTime> staffEmailSentDate { get; set; }
        public Nullable<System.DateTime> clientEmailSentDate { get; set; }
        public Nullable<System.DateTime> studentEmailSentDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        protected virtual ICollection<PriorityProjects> PriorityProjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        protected virtual ICollection<ProjectDocuments> ProjectDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        protected virtual ICollection<ProjectMethodsApplied> ProjectMethodsApplied { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        protected virtual ICollection<ProjectPeopleAllocations> ProjectPeopleAllocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        protected virtual ICollection<StudentProjectRanking> StudentProjectRanking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        protected virtual ICollection<ProjectEffortsApplied> ProjectEffortsApplied { get; set; }
        protected virtual ProjectStatus ProjectStatus1 { get; set; }
    }
}
