//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICTManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentProjectRanking
    {
        public int studentID { get; set; }
        public int projectID { get; set; }
        public int projectRank { get; set; }
    
        protected virtual Projects Projects { get; set; }
        protected virtual Students Students { get; set; }
    }
}
